### ISSUE TITLE
server cannot start

### ISSUE THREAD

**Issue by IshuCute** [o7Moon/OpenBoatUtils#37]
server just cant start with this mod.

[08:22:54] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'openboatutils'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.23.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.23.jar:?]

**Comment by nekowabo** [comment]
same error. I tried all versions
